name: tarea3
description: "Tarea 3"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  flutter_hooks: 0.21.2
  hooks_riverpod: ^2.6.1
  image_picker: ^1.1.2
  sqflite: ^2.4.2
  path: ^1.9.1
  dart_openai: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets: 
    - assets/images/
